#!/system/bin/sh
#system binary edition.
echo '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>MPEngine™8'
echo 'copyright by LENAROX.<<<<<<<<<<<<<<<<<<<<<<<<<<<'
echo 'help of minfree calculator thanks to zeppelinrox!'
echo 'this minfree calculator only sets the value for the top layer.'
echo 'in other words, give ME the credits!!!'
echo 'this engine makes your android ram management to rock like "Windows" does.'
echo 'it means no more lowmem lags;)'
echo 'ATTENTION!!! this engine was only confirmed working on linux kernel 2.6.x,'
echo 'therefore it may give bootloops on other unsupported versions.'
echo 'you must have the latest busybox version,'
echo 'installed on /system/xbin/ directory to run this engine.'
echo 'reminder: this engine is designed to run in the background with the android ram management,'
echo 'therefore it should NOT be used with other script applications.'
#gets rid of all kinds of dumbass resource fillers waaay faster.
#useful for this engine, since it only cleans page caches.
if [ -e /proc/sys/vm/vfs_cache_pressure ]
then
 /system/xbin/echo 100000 > /proc/sys/vm/vfs_cache_pressure
fi
#disables periodic writing.
if [ -e /proc/sys/vm/dirty_writeback_centisecs ]
then
 /system/xbin/echo 27640520 > /proc/sys/vm/dirty_writeback_centisecs
fi
if [ -e /proc/sys/vm/dirty_expire_centisecs ]
then
 /system/xbin/echo 0 > /proc/sys/vm/dirty_expire_centisecs
fi
#MPEngine™8 copyright by LENAROX.
#help of minfree calculator thanks to zeppelinrox!
#this minfree calculator only sets the value for the top layer.
#in other words, give ME the credits!!!
#these default settings below are actually based on my device,
#so i suggest you to tweak'em for your own needs.
##########tune your settings here##########
#MFKCUSTOM calculated multiplier.
#this is a calculated limit where the cache gets dropped.
#it is placed in top layer.
#for performance, increase the value.
#for battery life, decrease the value.
#decreasing the value to 0 turns off the engine.
VALUE0=1
#ENDOFTHEWORLD2 calculated multiplier.
#this is also a calculated cache limit,
#but it automatically changes its limit for best performance.
#it sits in between CUSTOMTOTAL and MEMINUSE.
#for performance, increase the value.
#for battery life, decrease the value.
#decreasing the value to 1 turns off the engine.
VALUE1=3
#sleep timer(sec).
#this lets you configure the amount of time for the engine to repeat.
#for performance, decrease the value.
#for battery life, increase the value.
#decreasing this value is very unstable for the battery.
VALUE2=20
###########################################
SSADJ=`getprop ro.SECONDARY_SERVER_ADJ`
if [ ! "$SSADJ" ]; then SSADJ=5; fi
minfree1=`awk -F , '{print $1}' /sys/module/lowmemorykiller/parameters/minfree`;minfree2=`awk -F , '{print $2}' /sys/module/lowmemorykiller/parameters/minfree`;minfree3=`awk -F , '{print $3}' /sys/module/lowmemorykiller/parameters/minfree`;minfree4=`awk -F , '{print $4}' /sys/module/lowmemorykiller/parameters/minfree`;minfree5=`awk -F , '{print $5}' /sys/module/lowmemorykiller/parameters/minfree`;minfree6=`awk -F , '{print $6}' /sys/module/lowmemorykiller/parameters/minfree`
oomadj1=`awk -F , '{print $1}' /sys/module/lowmemorykiller/parameters/adj`;oomadj2=`awk -F , '{print $2}' /sys/module/lowmemorykiller/parameters/adj`;oomadj3=`awk -F , '{print $3}' /sys/module/lowmemorykiller/parameters/adj`;oomadj4=`awk -F , '{print $4}' /sys/module/lowmemorykiller/parameters/adj`;oomadj5=`awk -F , '{print $5}' /sys/module/lowmemorykiller/parameters/adj`;oomadj6=`awk -F , '{print $6}' /sys/module/lowmemorykiller/parameters/adj`
if [ "$SSADJ" -le "$oomadj1" ]; then SSMF=$minfree1;slot=1;
elif [ "$SSADJ" -le "$oomadj2" ]; then SSMF=$minfree2;slot=2;
elif [ "$SSADJ" -le "$oomadj3" ]; then SSMF=$minfree3;slot=3;
elif [ "$SSADJ" -le "$oomadj4" ]; then SSMF=$minfree4;slot=4;
elif [ "$SSADJ" -le "$oomadj5" ]; then SSMF=$minfree5;slot=5;
elif [ "$SSADJ" -le "$oomadj6" ]; then SSMF=$minfree6;slot=6;
fi
MFKCUSTOM=$(($SSMF*4/5*$VALUE0))
MFK=`cat /proc/sys/vm/min_free_kbytes`
MFKLIMIT=$(($MFKCUSTOM-$MFK))
while true
do
FREEMEM=`free | awk '{ print $4 }' | sed -n 2p`
REALFREEMEM=$(($FREEMEM-$MFK))
CACHESIZE=`cat /proc/meminfo | grep Cached | awk '{print $2}' | sed -n 1p`
TOTALMEM=`free | awk '{ print $2 }' | sed -n 2p`
REALTOTALMEM=$(($TOTALMEM-$MFK))
COKE=$(($TOTALMEM-$FREEMEM))
CUSTOMTOTAL=$(($TOTALMEM-$MFKCUSTOM))
MEMINUSE=$(($TOTALMEM-$CACHESIZE-$FREEMEM))
DEATHLINE=$(($CUSTOMTOTAL-$MEMINUSE))
DEADEND=$(($DEATHLINE/$VALUE1))
ENDOFTHEWORLD2=$(($DEADEND+$MEMINUSE))
SKIP=$(($VALUE2/2))
#exception.
if [ $COKE -le $TOTALMEM -a $COKE -gt $REALTOTALMEM ]
then
echo 'running MPEngine™8: Exception(Err code 0)'
 /system/xbin/echo 1 > /proc/sys/vm/dirty_ratio
 /system/xbin/echo 100 > /proc/sys/vm/dirty_background_ratio
 /system/xbin/sync; /system/xbin/echo 1 > /proc/sys/vm/drop_caches
 /system/xbin/echo 3 > /proc/sys/vm/drop_caches
sleep $SKIP
 /system/xbin/sync; /system/xbin/echo 1 > /proc/sys/vm/drop_caches
 /system/xbin/echo 3 > /proc/sys/vm/drop_caches
sleep $SKIP
elif [ $COKE -le $REALTOTALMEM -a $COKE -gt $CUSTOMTOTAL -o $REALFREEMEM -lt $MFKLIMIT ]
then
echo 'running MPEngine™8: Aggressive Mode'
 /system/xbin/echo 1 > /proc/sys/vm/dirty_ratio
 /system/xbin/echo 100 > /proc/sys/vm/dirty_background_ratio
 /system/xbin/sync; /system/xbin/echo 1 > /proc/sys/vm/drop_caches
 /system/xbin/echo 3 > /proc/sys/vm/drop_caches
sleep $SKIP
 /system/xbin/sync; /system/xbin/echo 1 > /proc/sys/vm/drop_caches
 /system/xbin/echo 3 > /proc/sys/vm/drop_caches
sleep $SKIP
elif [ $COKE -le $CUSTOMTOTAL -a $COKE -gt $ENDOFTHEWORLD2 -a $REALFREEMEM -ge $MFKLIMIT ]
then
echo 'running MPEngine™8: Pre-Aggressive Mode'
#THE main special mode for this engine.
 /system/xbin/sync; /system/xbin/echo 1 > /proc/sys/vm/drop_caches
 /system/xbin/echo 3 > /proc/sys/vm/drop_caches
sleep $SKIP
 /system/xbin/sync; /system/xbin/echo 1 > /proc/sys/vm/drop_caches
 /system/xbin/echo 3 > /proc/sys/vm/drop_caches
sleep $SKIP
elif [ $COKE -le $ENDOFTHEWORLD2 -a $COKE -ge $MEMINUSE -o $REALFREEMEM -ge $MFKLIMIT ]
then
echo 'running MPEngine™8: Powersaver Mode'
 /system/xbin/echo 100 > /proc/sys/vm/dirty_ratio
 /system/xbin/echo 1 > /proc/sys/vm/dirty_background_ratio
sleep $VALUE2
#exception.
else
echo 'running MPEngine™8: Exception(Err code 1)'
 /system/xbin/echo 100 > /proc/sys/vm/dirty_ratio
 /system/xbin/echo 1 > /proc/sys/vm/dirty_background_ratio
sleep $VALUE2
fi
done
#go to http://forum.xda-developers.com/showthread.php?t=1978061 for more info.
#my e-mail: hoholee12@naver.com
